# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(847, 618)
        MainWindow.setMouseTracking(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.splitter_3 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.splitter = QtWidgets.QSplitter(self.splitter_3)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.widget = QtWidgets.QWidget(self.splitter)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lcdNumber = QtWidgets.QLCDNumber(self.widget)
        self.lcdNumber.setMinimumSize(QtCore.QSize(0, 123))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lcdNumber.setFont(font)
        self.lcdNumber.setObjectName("lcdNumber")
        self.verticalLayout.addWidget(self.lcdNumber)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setMinimumSize(QtCore.QSize(0, 20))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton = QtWidgets.QRadioButton(self.widget)
        self.radioButton.setMaximumSize(QtCore.QSize(16777215, 20))
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.widget)
        self.radioButton_2.setMaximumSize(QtCore.QSize(16777215, 20))
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout.addWidget(self.radioButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.textBrowser = QtWidgets.QTextBrowser(self.splitter)
        self.textBrowser.setMinimumSize(QtCore.QSize(0, 260))
        self.textBrowser.setObjectName("textBrowser")
        self.widget1 = QtWidgets.QWidget(self.splitter)
        self.widget1.setObjectName("widget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.widget1)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 21))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(85, 85, 127);")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.line_2 = QtWidgets.QFrame(self.widget1)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.label_2 = QtWidgets.QLabel(self.widget1)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 14))
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit.setMaximumSize(QtCore.QSize(16777215, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.pushButton_7 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_7.setMaximumSize(QtCore.QSize(16777215, 20))
        self.pushButton_7.setStyleSheet("background-color: rgb(170, 170, 127);")
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_2.addWidget(self.pushButton_7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.label_6 = QtWidgets.QLabel(self.widget1)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 14))
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.tableWidget = QtWidgets.QTableWidget(self.widget1)
        self.tableWidget.setMinimumSize(QtCore.QSize(0, 31))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout_2.addWidget(self.tableWidget)
        self.label_7 = QtWidgets.QLabel(self.widget1)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 14))
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7)
        self.line = QtWidgets.QFrame(self.widget1)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit_2.setMaximumSize(QtCore.QSize(16777215, 27))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_3.addWidget(self.lineEdit_2)
        self.pushButton_13 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_13.setMaximumSize(QtCore.QSize(16777215, 27))
        self.pushButton_13.setStyleSheet("background-color: rgb(85, 170, 127);")
        self.pushButton_13.setObjectName("pushButton_13")
        self.horizontalLayout_3.addWidget(self.pushButton_13)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.splitter_2 = QtWidgets.QSplitter(self.splitter_3)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.widget2 = QtWidgets.QWidget(self.splitter_2)
        self.widget2.setObjectName("widget2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.checkBox = QtWidgets.QCheckBox(self.widget2)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_3.addWidget(self.checkBox)
        self.pushButton_9 = QtWidgets.QPushButton(self.widget2)
        self.pushButton_9.setStyleSheet("background-color: rgb(170, 170, 127);")
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout_3.addWidget(self.pushButton_9)
        self.pushButton = QtWidgets.QPushButton(self.widget2)
        self.pushButton.setStyleSheet("background-color: rgb(0, 85, 0);\n"
"background-color: rgb(85, 170, 127);")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_3.addWidget(self.pushButton)
        self.pushButton_10 = QtWidgets.QPushButton(self.widget2)
        self.pushButton_10.setObjectName("pushButton_10")
        self.verticalLayout_3.addWidget(self.pushButton_10)
        self.pushButton_8 = QtWidgets.QPushButton(self.widget2)
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_3.addWidget(self.pushButton_8)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_3.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_3.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.widget2)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_3.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.widget2)
        self.pushButton_5.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.pushButton_5.setCheckable(False)
        self.pushButton_5.setFlat(False)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_3.addWidget(self.pushButton_5)
        self.calendarWidget = QtWidgets.QCalendarWidget(self.splitter_2)
        self.calendarWidget.setObjectName("calendarWidget")
        self.widget3 = QtWidgets.QWidget(self.splitter_2)
        self.widget3.setObjectName("widget3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_6 = QtWidgets.QPushButton(self.widget3)
        self.pushButton_6.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_4.addWidget(self.pushButton_6)
        self.pushButton_11 = QtWidgets.QPushButton(self.widget3)
        self.pushButton_11.setAutoFillBackground(False)
        self.pushButton_11.setStyleSheet("background-color: rgb(85, 170, 0);")
        self.pushButton_11.setObjectName("pushButton_11")
        self.verticalLayout_4.addWidget(self.pushButton_11)
        self.pushButton_12 = QtWidgets.QPushButton(self.widget3)
        self.pushButton_12.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.pushButton_12.setObjectName("pushButton_12")
        self.verticalLayout_4.addWidget(self.pushButton_12)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.widget3)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.verticalLayout_4.addWidget(self.doubleSpinBox)
        self.checkBox_6 = QtWidgets.QCheckBox(self.widget3)
        self.checkBox_6.setObjectName("checkBox_6")
        self.verticalLayout_4.addWidget(self.checkBox_6)
        self.checkBox_5 = QtWidgets.QCheckBox(self.widget3)
        self.checkBox_5.setObjectName("checkBox_5")
        self.verticalLayout_4.addWidget(self.checkBox_5)
        self.checkBox_4 = QtWidgets.QCheckBox(self.widget3)
        self.checkBox_4.setObjectName("checkBox_4")
        self.verticalLayout_4.addWidget(self.checkBox_4)
        self.checkBox_3 = QtWidgets.QCheckBox(self.widget3)
        self.checkBox_3.setObjectName("checkBox_3")
        self.verticalLayout_4.addWidget(self.checkBox_3)
        self.checkBox_2 = QtWidgets.QCheckBox(self.widget3)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout_4.addWidget(self.checkBox_2)
        self.graphicsView = QtWidgets.QGraphicsView(self.splitter_2)
        self.graphicsView.setObjectName("graphicsView")
        self.horizontalLayout_4.addWidget(self.splitter_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 847, 28))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "EMD - Natural Metrics Descriptor  [Ultra k2]", "EMD-NMDS"))
        self.label_3.setText(_translate("MainWindow", "N/A"))
        self.label.setText(_translate("MainWindow", "Current Air Temprature"))
        self.radioButton.setText(_translate("MainWindow", "Deg (C)"))
        self.radioButton_2.setText(_translate("MainWindow", "Deg (F)"))
        self.label_4.setText(_translate("MainWindow", "EMD - NMS"))
        self.label_2.setText(_translate("MainWindow", "Select location:"))
        self.pushButton_7.setText(_translate("MainWindow", "Search"))
        self.label_6.setText(_translate("MainWindow", "Results"))
        self.label_7.setText(_translate("MainWindow", "GPDE INPUT"))
        self.pushButton_13.setText(_translate("MainWindow", "SET"))
        self.checkBox.setText(_translate("MainWindow", "PORT1"))
        self.pushButton_9.setText(_translate("MainWindow", "Back"))
        self.pushButton.setText(_translate("MainWindow", "Select"))
        self.pushButton_10.setText(_translate("MainWindow", "DOK"))
        self.pushButton_8.setText(_translate("MainWindow", "CQ"))
        self.pushButton_2.setText(_translate("MainWindow", "ACK"))
        self.pushButton_3.setText(_translate("MainWindow", "STAT"))
        self.pushButton_4.setText(_translate("MainWindow", "QUEUE"))
        self.pushButton_5.setToolTip(_translate("MainWindow", "Reload Whole  Window"))
        self.pushButton_5.setWhatsThis(_translate("MainWindow", "Reload This Whole Window"))
        self.pushButton_5.setText(_translate("MainWindow", "RELOAD"))
        self.pushButton_6.setText(_translate("MainWindow", "LOCK"))
        self.pushButton_11.setText(_translate("MainWindow", "RELEASE"))
        self.pushButton_12.setText(_translate("MainWindow", "FETCH"))
        self.checkBox_6.setText(_translate("MainWindow", "COM1"))
        self.checkBox_5.setText(_translate("MainWindow", "COM2"))
        self.checkBox_4.setText(_translate("MainWindow", "COM3"))
        self.checkBox_3.setText(_translate("MainWindow", "COM4"))
        self.checkBox_2.setText(_translate("MainWindow", "COM5"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

